version: '3'
services:
  postgres-order:
    container_name: postgres-order
    image: postgres
    environment:
      POSTGRES_DB: order-service
      POSTGRES_USER: habbal
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
     - ./postgres-order:/data/postgres
    expose:
     - "5431"
    ports:
     - "5431:5431"
    command: -p 5431
    restart: unless-stopped
  postgres-inventory:
    container_name: postgres-inventory
    image: postgres
    environment:
      POSTGRES_DB: inventory-service
      POSTGRES_USER: habbal
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
     - ./postgres-inventory:/data/postgres
    ports:
     - "5432:5432"
    restart: unless-stopped
  mongo:
    container_name: mongo
    image: mongo:4.4.14-rc0-focal
    restart: unless-stopped
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./mongo-data:/data/db
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:20.0.2
    command:
      - "start-dev"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - ./realms/:/opt/keycloak/data/import/
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

